create table BOOTS
(
    CODE        INTEGER       not null
        primary key,
    NAME        VARCHAR(100)  not null,
    TYPE        VARCHAR(20)   not null,
    DESCRIPTION VARCHAR(1000) not null,
    SIZE        INTEGER       not null,
    COLOR       VARCHAR(15)   not null,
    PRICE       NUMERIC(6, 2) not null,
    BRAND       VARCHAR(30)   not null
);

INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (1, 'Off-Piste Extreme Mens Snowboots', 'snow', 'The Off-Piste Mens Snowboots are extremely warm and durable. They''re snowproof, have a suede upper, IsoTherm lining and a sturdy rubber outsole - these boots are the best way to keep your feet protected this winter.', 42, 'Black', 59.99, 'Mountain Warehouse');
INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (2, 'Ohio Womens Snow Boots', 'snow', 'The Ohio Snow Boots are warm and snowproof. The IsoTherm lining has been tested to keep your feet warm in temperatures as low as -20_C. The durable womens boot is a stylish and practical addition to your winter wardrobe.', 41, 'Grey', 65.99, 'Mountain Warehouse');
INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (3, 'Olang Canadian Unisex', 'snow', 'Unisex snow boot. Rugged faux suede and nylon outer. Adjustable tongue and lace closure. Durable, high grip sole unit. Warm sherpa fleece lining. Corded cuff seals against snow', 38, 'Anthracite', 95.00, 'Olang');
INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (11001, 'Kayland Unisex Cumbria Gore-Tex - Brown', 'forest', 'Mid-cut shoes, ideal for light trekking and walks on multiple surfaces as well as for everyday work. Soft nubuck leather upper, durable and resistant to the elements, combined with Gore-Tex_ Performance Comfort membrane to provide waterproof protection while improving breathability. Injected PU midsole and Vibram_ New Makalu tread pattern, developed to offer excellent grip even on slippery surfaces.', 44, 'Brown', 150.00, 'Kayland');
INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (11002, 'Merrell Men''s Moab 2 Leather Mid Gore-Tex', 'forest', 'Experience out-of-the-box comfort in this GORE-TEX hiker. With durable leathers, a supportive footbed, and Vibram traction, the Moab has been worn on the feet of nearly 20 million people since its inception', 46, 'Tan', 155.00, 'Merrell');
INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (11003, 'Women''s warm waterproof hiking shoes - sh520 x-warm mid', 'forest', 'Want to climb snowy slopes? We have designed this warm, waterproof shoe for hikers, offering the perfect grip for walking in the mountains. These waterproof and warm shoes will provide you with very good hold for snowshoeing. The snowcontact sole offers excellent traction and grip on all types of snow-covered terrain.', 37, 'Black', 35.00, 'Quechua');
INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (22001, 'Site Trench Safety Wellies', 'wellington', '100% virgin PVC, ribbed upper. Practical with a comfortable, lined inner. Ideal for farming and industrial applications.', 44, 'Black', 20.95, 'Site');
INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (22002, 'Baudou Major Green Wellingtons', 'wellington', 'A comfortable, lightweight, durable green rubber wellington boot. It''s a waterproof boot with excellent sole grip. EU size 41.', 41, 'Green', 36.00, 'Baudou');
INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (33001, 'Fastnet Sailing Boot - Carbon', 'water', 'A lightweight, athletic design with outstanding technical performance, Dubarry''s Fastnet sailing boots are not just waterproof, with a breathable membrane; they''re impressively shock-absorbent too. The removable footbed provides extra cushioning and the D-Chassis_ system delivers additional support, protection and control for heels and toes while preserving your agility. The award-winning NonSlip-NonMarking_ rubber outsole has a unique water dispersion channel system to eliminate the risk of aquaplaning on wet decks.', 38, 'Carbon', 299.00, 'Dubarry');
INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (33002, 'Musto Southern Ocean Sailing Boots', 'water', 'The Southern Ocean Boot: complete attention to detail tailored towards the most punishing environments on the planet. The highest possible content of natural rubber ensures unyielding waterproof protection. For exceptional comfort and warmth, a hardwearing 3mm neoprene lining and an integral fabric gaiter prevents water entering the boots. A superior outsole compound delivers superb grip and traction on-deck while safeguarding. Designed, developed and tested by Volvo Ocean Race Sailors in the Southern Ocean.', 42, 'Black', 159.99, 'Musto');
INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (44001, '1460 Pascal Virginia Leather Ankle Boots', 'fashion', 'More shades from the DM''s archive: each season, we enhance our Originals collection with additionalcolours inspired by classic Docs designs. Made from Virginia, a grained leather that feels worn in from the first step, these boots stay true to their six-decade-old construction with yellow welt stitching, a scripted AirWair heel loop and a tough air-cushioned outsole.', 36, 'White', 189.99, 'Dr Martens');
INSERT INTO DBA.BOOTS (CODE, NAME, TYPE, DESCRIPTION, SIZE, COLOR, PRICE, BRAND) VALUES (44002, 'R.M. Williams Classic Craftsman Boots - Yearling Leather, Classic Leather Sole', 'fashion', 'One of R.M. Williams''s signature products, the men''s R.M. Williams Craftsman Boots are a high quality and handmade version of the classic Chelsea boots. The boots are crafted from just one piece of the finest yearling leather, giving a seamless and smooth design all over the boots, as well as a quality and comfortable finish and fit. Keeping things classic, the boots have a square toe, as well as a flat heel and feature sewn welt classic leather sole. The tops of the boots have two branded tabs, making it easy to get in and out of the boots, as well as adding a signature finish. The Chelsea boot design is timeless and works with a wide variety of outfits and seasons, and the R.M. Williams boots are sure you keep you looking stylish for many years to come.', 40, 'Chestnut', 375.00, 'R.M. Williams');
